import type {
  IVideoPreviewCacheRepository,
  PreviewCacheWrite,
  VideoPreviewProduct,
  VideoPreviewProducts,
} from '@domain/repositories/IVideoPreviewCacheRepository'
import {
  hasCompleteKeyframes,
  hasCompleteMotionClips,
  KEYFRAME_PREVIEW_VERSION,
  MOTION_PREVIEW_VERSION,
  MOTION_FALLBACK_VERSION,
  hasCompleteMotionFallback,
} from '@domain/services/videoPreviewPolicy'
import type { ILogger } from '@app/ports'

export const PREVIEW_CACHE_DATABASE = 'BVRPreviewCache-v1'
export const PREVIEW_CACHE_BYTES = 256 * 1024 * 1024
const STORE = 'products'
type CacheRecord = {
  key: string
  duration: number
  product: VideoPreviewProduct
  lastUsed: number
  bytes: number
}
type CacheEntry = { key: string; bytes: number }
const cacheKey = (
  id: string,
  kind: VideoPreviewProduct['kind'],
  version: string,
) => JSON.stringify([id, kind, version])
const emptyProducts = (): VideoPreviewProducts => ({
  motionClips: [],
  keyframes: [],
  previewVersions: {},
})
function isValid(duration: number, product: VideoPreviewProduct) {
  if (product?.kind === 'motionClips')
    return hasCompleteMotionClips({
      duration,
      motionClips: product.items,
      previewVersions: { motionClips: product.version },
    })
  if (product?.kind === 'keyframes')
    return hasCompleteKeyframes({
      duration,
      keyframes: product.items,
      previewVersions: { keyframes: product.version },
    })
  if (product?.kind === 'motionFallback')
    return hasCompleteMotionFallback({ duration, motionFallback: product })
  return false
}

/** Entries are ordered by last use. Only encoded, generated bytes count here. */
export function selectCacheEvictions(
  entries: CacheEntry[],
  replacingKey: string,
  incomingBytes: number,
  limit = PREVIEW_CACHE_BYTES,
): string[] {
  if (incomingBytes > limit) throw new Error('cache-product-too-large')
  let total =
    incomingBytes +
    entries.reduce(
      (sum, entry) => sum + (entry.key === replacingKey ? 0 : entry.bytes),
      0,
    )
  const evicted: string[] = []
  for (const entry of entries) {
    if (total <= limit) break
    if (entry.key === replacingKey) continue
    evicted.push(entry.key)
    total -= entry.bytes
  }
  return evicted
}

export class VideoPreviewCacheRepository
  implements IVideoPreviewCacheRepository
{
  private connection?: Promise<IDBDatabase>
  private writeEpoch = 0
  private readonly writes = new Set<IDBTransaction>()
  constructor(private readonly logger: Pick<ILogger, 'warn'>) {}
  get epoch() {
    return this.writeEpoch
  }

  private connect(): Promise<IDBDatabase> {
    if (this.connection) return this.connection
    const opening = new Promise<IDBDatabase>((resolve, reject) => {
      let finished = false
      const request = indexedDB.open(PREVIEW_CACHE_DATABASE, 1)
      request.onupgradeneeded = () => {
        const store = request.result.createObjectStore(STORE, {
          keyPath: 'key',
        })
        // Key cursors expose byte accounting without loading cached Blob values.
        store.createIndex('usage', ['lastUsed', 'bytes'])
      }
      request.onsuccess = () => {
        if (finished) {
          request.result.close()
          return
        }
        finished = true
        const db = request.result
        db.onversionchange = () => {
          db.close()
          this.connection = undefined
        }
        resolve(db)
      }
      const fail = (error: Error | DOMException) => {
        if (finished) return
        finished = true
        reject(error)
      }
      request.onerror = () =>
        fail(request.error ?? new Error('preview-cache-unavailable'))
      // error is inaccessible while an open request is still pending (including blocked).
      request.onblocked = () => fail(new Error('preview-cache-blocked'))
    })
    this.connection = opening
    void opening.catch(() => {
      if (this.connection === opening) this.connection = undefined
    })
    return opening
  }

  private assertOwnership(ownership: PreviewCacheWrite) {
    ownership.signal.throwIfAborted()
    if (ownership.epoch !== this.epoch)
      throw new DOMException('Preview work retired', 'AbortError')
  }

  private transaction(
    db: IDBDatabase,
    work: (store: IDBObjectStore, fail: (error: unknown) => void) => void,
    signal?: AbortSignal,
  ): Promise<void> {
    return new Promise((resolve, reject) => {
      const transaction = db.transaction(STORE, 'readwrite')
      this.writes.add(transaction)
      let failure: unknown
      const abort = () => {
        try {
          transaction.abort()
        } catch {
          /* Already completed; ownership is checked by the caller. */
        }
      }
      const cleanup = () => {
        this.writes.delete(transaction)
        signal?.removeEventListener('abort', abort)
      }
      transaction.oncomplete = () => {
        cleanup()
        resolve()
      }
      transaction.onabort = transaction.onerror = () => {
        cleanup()
        reject(
          failure ??
            transaction.error ??
            new DOMException('Preview transaction aborted', 'AbortError'),
        )
      }
      signal?.addEventListener('abort', abort, { once: true })
      if (signal?.aborted) {
        abort()
        return
      }
      const fail = (error: unknown) => {
        failure = error
        abort()
      }
      try {
        work(transaction.objectStore(STORE), fail)
      } catch (error) {
        fail(error)
      }
    })
  }

  async getProducts(
    videoId: string,
    duration: number,
  ): Promise<VideoPreviewProducts> {
    const epoch = this.epoch
    const db = await this.connect()
    if (epoch !== this.epoch) return emptyProducts()
    const products = emptyProducts()
    const hits: CacheRecord[] = []
    let readsCompleted = 0
    try {
      await this.transaction(db, (store, fail) => {
        for (const [kind, version] of [
          ['motionClips', MOTION_PREVIEW_VERSION],
          ['keyframes', KEYFRAME_PREVIEW_VERSION],
          ['motionFallback', MOTION_FALLBACK_VERSION],
        ] as const) {
          const request = store.get(
            cacheKey(videoId, kind, version),
          ) as IDBRequest<CacheRecord | undefined>
          request.onsuccess = () => {
            try {
              const record = request.result
              if (
                record &&
                record.duration === duration &&
                record.product?.kind === kind &&
                isValid(duration, record.product)
              ) {
                if (record.product.kind === 'motionClips')
                  products.motionClips = record.product.items
                else if (record.product.kind === 'keyframes')
                  products.keyframes = record.product.items
                else {
                  const { version, reason, items } = record.product
                  products.motionFallback = { version, reason, items }
                }
                if (kind !== 'motionFallback')
                  products.previewVersions[kind] = version
                hits.push(record)
              }
              readsCompleted++
              // Finish all reads before optional touches, which cannot undo immutable hits.
              if (readsCompleted === 3)
                for (const hit of hits)
                  store.put({ ...hit, lastUsed: Date.now() })
            } catch (error) {
              fail(error)
            }
          }
        }
      })
    } catch (error) {
      if (readsCompleted !== 3) throw error
      this.logger.warn('[preview-cache] last-used-update:failed')
    }
    return epoch === this.epoch ? products : emptyProducts()
  }

  async putProduct(
    videoId: string,
    duration: number,
    product: VideoPreviewProduct,
    ownership: PreviewCacheWrite,
  ): Promise<void> {
    this.assertOwnership(ownership)
    if (!isValid(duration, product)) throw new Error('invalid-preview-product')
    const bytes = product.items.reduce((sum, item) => sum + item.blob.size, 0)
    const key = cacheKey(videoId, product.kind, product.version)
    const db = await this.connect()
    this.assertOwnership(ownership)
    await this.transaction(
      db,
      (store, fail) => {
        const entries: CacheEntry[] = []
        const request = store.index('usage').openKeyCursor()
        request.onsuccess = () => {
          try {
            this.assertOwnership(ownership)
            const cursor = request.result
            if (cursor) {
              entries.push({
                key: String(cursor.primaryKey),
                bytes: (cursor.key as number[])[1],
              })
              cursor.continue()
              return
            }
            for (const expired of selectCacheEvictions(entries, key, bytes))
              store.delete(expired)
            store.put({
              key,
              duration,
              product,
              bytes,
              lastUsed: Date.now(),
            } satisfies CacheRecord)
          } catch (error) {
            // Abort the entire transaction, including any evictions; never commit a partial replacement.
            fail(error)
          }
        }
      },
      ownership.signal,
    )
    this.assertOwnership(ownership)
  }

  async clear(): Promise<void> {
    this.writeEpoch++
    for (const transaction of this.writes) {
      try {
        transaction.abort()
      } catch {
        /* A completed transaction cannot repopulate after the clear below. */
      }
    }
    const db = await this.connect()
    await this.transaction(db, (store) => {
      store.clear()
    })
  }
}
